"""initial

Revision ID: fc852a2967a8
Revises: 
Create Date: 2026-05-28 01:57:49.711796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc852a2967a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_archetype', sa.Text(), nullable=False),
    sa.Column('lesson_type', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('source_debate_id', sa.String(), nullable=True),
    sa.Column('source_session_id', sa.String(), nullable=True),
    sa.Column('embedding_blob', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_exp_archetype', 'agent_experiences', ['agent_archetype'], unique=False)
    op.create_index('idx_agent_exp_used', 'agent_experiences', ['last_used_at'], unique=False)
    op.create_table('cost_rates',
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('input_rate_per_1m', sa.Float(), nullable=True),
    sa.Column('output_rate_per_1m', sa.Float(), nullable=True),
    sa.Column('pricing_available', sa.Boolean(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('model')
    )
    op.create_table('council_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intelligence_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('debate_id', sa.String(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('team', sa.Text(), nullable=True),
    sa.Column('agent_role', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intelligence_debate', 'intelligence_records', ['debate_id'], unique=False)
    op.create_index('idx_intelligence_type', 'intelligence_records', ['type', 'agent_role'], unique=False)
    op.create_table('runtime_diary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runtime_event', 'runtime_diary', ['event'], unique=False)
    op.create_index('idx_runtime_session', 'runtime_diary', ['session_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('active_debate_id', sa.String(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('token_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('debate_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('agent_role', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('converted_cost', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_events_debate', 'token_events', ['debate_id'], unique=False)
    op.create_index('idx_token_events_session', 'token_events', ['session_id'], unique=False)
    op.create_table('user_debate_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('debates_completed', sa.Integer(), nullable=True),
    sa.Column('practice_debates_completed', sa.Integer(), nullable=True),
    sa.Column('wins_json', sa.Text(), nullable=True),
    sa.Column('side_history_json', sa.Text(), nullable=True),
    sa.Column('strengths_json', sa.Text(), nullable=True),
    sa.Column('weaknesses_json', sa.Text(), nullable=True),
    sa.Column('trainer_notes_json', sa.Text(), nullable=True),
    sa.Column('style_tags_json', sa.Text(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('debates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('pro_position', sa.Text(), nullable=True),
    sa.Column('con_position', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('assignments_json', sa.Text(), nullable=True),
    sa.Column('judge_config_json', sa.Text(), nullable=True),
    sa.Column('analytics_json', sa.Text(), nullable=True),
    sa.Column('cost_summary_json', sa.Text(), nullable=True),
    sa.Column('practice_state_json', sa.Text(), nullable=True),
    sa.Column('phase_graph_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_debates_session_status', 'debates', ['session_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('debate_id', sa.String(), nullable=True),
    sa.Column('stream_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('team', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_debate', 'messages', ['debate_id'], unique=False)
    op.create_index('idx_messages_session', 'messages', ['session_id'], unique=False)
    op.create_index('idx_messages_stream', 'messages', ['stream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_stream', table_name='messages')
    op.drop_index('idx_messages_session', table_name='messages')
    op.drop_index('idx_messages_debate', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_debates_session_status', table_name='debates')
    op.drop_table('debates')
    op.drop_table('user_debate_profiles')
    op.drop_index('idx_token_events_session', table_name='token_events')
    op.drop_index('idx_token_events_debate', table_name='token_events')
    op.drop_table('token_events')
    op.drop_table('sessions')
    op.drop_index('idx_runtime_session', table_name='runtime_diary')
    op.drop_index('idx_runtime_event', table_name='runtime_diary')
    op.drop_table('runtime_diary')
    op.drop_index('idx_intelligence_type', table_name='intelligence_records')
    op.drop_index('idx_intelligence_debate', table_name='intelligence_records')
    op.drop_table('intelligence_records')
    op.drop_table('council_settings')
    op.drop_table('cost_rates')
    op.drop_index('idx_agent_exp_used', table_name='agent_experiences')
    op.drop_index('idx_agent_exp_archetype', table_name='agent_experiences')
    op.drop_table('agent_experiences')
    # ### end Alembic commands ###
